name: Docker Image CI

on:
  pull_request:
    branches: [ docker ]
    paths:
      - 'docker/requirements.nightly.txt'
      - 'docker/Dockerfile.nightly'

jobs:

  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # use buildx for crossplaform build
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.nightly
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: |
          ubsuny/compphys:nighly
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
