name: Docker Image CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'install_software.sh'
      - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # use buildx for crossplaform build
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Build the Docker image
      run: docker build --platform linux/amd64,linux/arm/v7 --file Dockerfile --tag ubsuny/compphys:nightly
